@startuml

actor Student as "Stajyer Öğrenci"
participant Department as "Bölüm"
participant Faculty as "Fakülte"
participant Rector as "Rektörlük"
participant Company as "Firma"
participant Government as "E-Devlet"

autonumber 1 1 "<font color=red><b>Adim-0  "

== FİRMA ARAMA == 

Student -> Student : Staj başlangıç ve bitiş tarihinizi verilen tabloya göre planlayın

Student -> Student : Başvuracağınız Firma Listesini Oluşturun

Student -> Firma : Staj başlangıç ve bitiş tarihinize göre firmalardan onay alarak listenizi daraltın

Student -> Department : Bölümden Staj Yapılabilirliğine Dair Teyit Alın (Hocalarınız ile Görüşün)

== STAJ ÖNCESİ == 

Student -> Department : [[http://bilgisayar.mmf.erdogan.edu.tr/tr/page/staj-islemleri/5497 {İndirmek için Tıklayın} Başvuru Formunu İndirin ]] 

Student -> Department : [[https://mmf.erdogan.edu.tr/Files/ckFiles/muhendislik-erdogan-edu-tr/M%C3%BChendislik%20Fak%C3%BCltesi%20%C4%B0%C5%9F%20yeri%20Staj%20S%C3%B6zle%C5%9Fmesi.pdf {İndirmek için Tıklayın} İş Yeri Staj Sözleşmesini İndirin ]]  (iş yerine imzalatılacak)

Student -> Government :  [[https://www.turkiye.gov.tr/spas-mustahaklik-sorgulama Müstahaklık  Belgesi'ni Temin Edin]] (E- Devlet veya SGK’dan temin edilebilir)

note across

[[https://ekampus.erdogan.edu.tr/welcome  {İndirmek için Tıklayın} Başvuru Formunu İndirin ]] 

Staj Başvuru Evrakları, 
Staj Başlangıç tarihinden  
- en az 3 hafta önce komisyona
- en az 10 gün önce Öğrenci İşlerine 
teslim edilmelidir.

Evrak Listesi
- Başvuru Formu
- İş Yeri Sözleşmesi
- Müstahaklık Belgesi

end note

Student -> Student : Staj Başvuru Formunda yer alan şahsi bilgiler; tedaviden yararlanma  durumu ve staj süresi ile ilgili bilgiler öğrenci tarafından doldurulacaktır.

Student -> Firma : Staj Başvuru Formunun sağ alt kısmında yer alan “Staj Yapılan Kurum / İş Yeri Bilgileri” kısmı öğrenci tarafından ilgili yere doldurulacaktır.

Student -> Firma : Staj başlangıç ve bitiş tarihini aşağıdaki tabloya  göre doğru şekilde yazınız ve onaylatınız. aksi halde yeni bir form vermeniz gerekeceğinden tekrar ilgili kurum/şirket onayı almanız gerekir.

Student -> Student : Staj Başvuru Formunun sol alt kısmında yer alan bölgede öğrenci kendi imzasını atacak

Student -> Department : Staj Başvuru Formunun'da “BÖLÜM STAJ ONAYI” kısmını da öğrencinin kendisi Bölüm Staj Komisyon Başkanına onaylatacaktır.

note over Department

Posta yolu ile gönderenler Bölüm Staj Onayı kısmını boş bırakabilir.

end note 

== STAJ BAŞVURUSUNDA ==

Student --> Department : Evrak Teslimi Bölüm Staj Komisyonu ve ardından Öğrenci İşlerine Teslim Edilir

== STAJ SÜRESİNCE ==

Student -> Firma : Staj İçeriğine Uygun Proje ve Uygulama Yapılması

Student -> Student : Staj Süresince Düzenli Çalışmaların Raporlanması

== STAJ SONRASI == 

Student --> Department : Staj Dosyası Teslimi (Bölüm Staj Komisyonu)

note over Department

Staj Dosyaı Son Tarihi için Güz dönemi takvimi takip edilecektir.

end note
@enduml
